version: "3.3"
services:

  api_gateway:
    image: nginx:1.17.10
    container_name: nginx_api_gateway
    depends_on:
        - order_service
        - store_service
        - menu_service
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./api_gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
      - ./api_gateway/api_backends.conf:/etc/nginx/api_backends.conf
      - ./api_gateway/api_json_errors.conf:/etc/nginx/api_json_errors.conf
      - ./api_gateway/api_keys.conf:/etc/nginx/api_keys.conf
      - ./api_gateway/api_conf.d:/etc/nginx/api_conf.d/
      - ./api_gateway/log:/var/log/nginx/log/
    ports:
      - 80:80


  store_mongo:
    image: mongo
    container_name: store_mongo
    command: mongod --port 20002
    ports:
      - "20002:20002"
    environment:
      MONGO_INITDB_ROOT_USERNAME: comp3122
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./store_service/store-mongo-init.js:/docker-entrypoint-initdb.d/store-mongo-init.js
      - store_mongo_volume:/data/db

  store_service:
    build: ./store_service
    container_name: store_service
    ports:
      - "15002:15002"
    environment:
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
      MONGO_SERVER_HOST: store_mongo
      MONGO_SERVER_PORT: 20002
    depends_on:
      - store_mongo
    restart: on-failure

  menu_mongo:
    image: mongo
    container_name: menu_mongo
    command: mongod --port 20003
    ports:
      - "20003:20003"
    environment:
      MONGO_INITDB_ROOT_USERNAME: comp3122
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./menu_service/menu-mongo-init.js:/docker-entrypoint-initdb.d/menu-mongo-init.js
      - menu_mongo_volume:/data/db

  menu_service:
    build: ./menu_service
    container_name: menu_service
    ports:
      - "15003:15003"
    environment:
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
      MONGO_SERVER_HOST: menu_mongo
      MONGO_SERVER_PORT: 20003
    depends_on:
      - menu_mongo
    restart: on-failure

  
  order_mongo:
    image: mongo
    container_name: order_mongo
    command: mongod --port 20004
    ports:
      - "20004:20004"
    environment:
      MONGO_INITDB_ROOT_USERNAME: comp3122
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./order_service/order-mongo-init.js:/docker-entrypoint-initdb.d/order-mongo-init.js
      - order_mongo_volume:/data/db

  order_service:
    build: ./order_service
    container_name: order_service
    ports:
      - "15004:15004"
    environment:
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
      MONGO_SERVER_HOST: order_mongo
      MONGO_SERVER_PORT: 20004
    depends_on:
      - order_mongo
    restart: on-failure

networks:
  default:
    name: project

volumes:
  order_mongo_volume:
    name: order_mongo_vol
  store_mongo_volume:
    name: store_mongo_vol
  menu_mongo_volume:
    name: menu_mongo_vol