version: "3.3"
services:
  store_mongo:
    image: mongo
    container_name: store_db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: comp3122
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_volume:/data/store_db
  store_service:
    build: ./store_service
    container_name: store_service
    ports:
      - "15001:15000"
    environment:
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
      MONGO_SERVER_HOST: store_mongo
      MONGO_SERVER_PORT: 27018
    depends_on:
      - store_mongo
  menu_mongo:
    image: mongo
    container_name: menu_db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: comp3122
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_volume:/data/menu_db
  menu_service:
    build: ./menu_service
    container_name: menu_service
    ports:
      - "15002:15000"
    environment:
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
      MONGO_SERVER_HOST: menu_mongo
      MONGO_SERVER_PORT: 27019
    depends_on:
      - menu_mongo
  order_mongo:
    image: mongo
    container_name: order_db
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: comp3122
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_volume:/data/order_db
  order_service:
    container_name : order_service
    environment:
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
      MONGO_SERVER_HOST: 'order_mongo'
      MONGO_SERVER_PORT: '27020'
    build: ./order_service
    depends_on:
      - order_mongo
    ports:
      - "15003:15000"
    restart: on-failure
  api_gateway:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
      - store_service
      - menu_service
      - order_service
      - cart_service
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80


  cart_service:
    environment:
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
      MONGO_SERVER_HOST: 'mongo'
      MONGO_SERVER_PORT: '27017'
    build: ./cart_service
    ports:
      - 15001:15001
    links:
      - mongo
    restart: on-failure

networks:
  default:
    name: project

volumes:
  mongo_volume:
    name: mongo_vol
