version: "3.3"
services:

  api_gateway:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
        - order_service
        - cart_service
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80


  mongo:
    image: mongo
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: comp3122
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_volume:/data/db

  order_service:
    container_name: order_service
    environment:
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
      MONGO_SERVER_HOST: 'mongo'
      MONGO_SERVER_PORT: '27017'
    build: ./order_service
    ports:
      - 15000:15000
    links:
      - mongo
    restart: on-failure

  cart_service:
    container_name: cart_service
    environment:
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
      MONGO_SERVER_HOST: 'mongo'
      MONGO_SERVER_PORT: '27017'
    build: ./cart_service
    ports:
      - 15001:15001
    links:
      - mongo
    restart: on-failure

  account_service:
    container_name: account_service
    environment:
      MONGO_USERNAME: comp3122
      MONGO_PASSWORD: 12345
      MONGO_SERVER_HOST: 'mongo'
      MONGO_SERVER_PORT: '27017'
    build: ./account_service
    ports:
      - 15002:15002
    links:
      - mongo
    restart: on-failure
    
networks:
  default:
    name: project

volumes:
  mongo_volume:
    name: mongo_vol
