# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'order_service'
    scrape_interval: 10s
    static_configs:
      - targets: ['order_service:15004']
  - job_name: 'store_service'
    scrape_interval: 10s
    static_configs:
      - targets: ['store_service:15002']
  - job_name: 'menu_service'
    scrape_interval: 10s
    static_configs:
      - targets: ['menu_service:15003']
  - job_name: 'account_service'
    scrape_interval: 10s
    static_configs:
      - targets: ['account_service:15001']
  - job_name: 'delivery_service'
    scrape_interval: 10s
    static_configs:
      - targets: ['delivery_service:15005']
  - job_name: 'api_gateway'
    scrape_interval: 10s
    static_configs:
      - targets: ['nginx-exporter:9113']

alerting:
 alertmanagers:
 - static_configs:
   - targets: ["alertmanager:9093"]

