# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
datasources:
  # name of the datasource
- name: Prometheus
  # datasource type
  type: prometheus
  # access mode. direct or proxy
  access: proxy
  # org id
  orgId: 1
  # url
  url: http://prometheus:9090
  # enable basic auth
  basicAuth: true
  # basic auth username
  basicAuthUser: admin
  # basic auth password
  basicAuthPassword: foobar
  # fields that will be converted to json and stored in json_data
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  # json object of data that will be encrypted
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  # allow users to edit datasources from the UI
  editable: true